package workloads

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/autorest/validation"
	"github.com/Azure/go-autorest/tracing"
	"net/http"
)

// SAPCentralInstancesClient is the client for the SAPCentralInstances methods of the Workloads service.
type SAPCentralInstancesClient struct {
	BaseClient
}

// NewSAPCentralInstancesClient creates an instance of the SAPCentralInstancesClient client.
func NewSAPCentralInstancesClient(subscriptionID string) SAPCentralInstancesClient {
	return NewSAPCentralInstancesClientWithBaseURI(DefaultBaseURI, subscriptionID)
}

// NewSAPCentralInstancesClientWithBaseURI creates an instance of the SAPCentralInstancesClient client using a custom
// endpoint.  Use this when interacting with an Azure cloud that uses a non-standard base URI (sovereign clouds, Azure
// stack).
func NewSAPCentralInstancesClientWithBaseURI(baseURI string, subscriptionID string) SAPCentralInstancesClient {
	return SAPCentralInstancesClient{NewWithBaseURI(baseURI, subscriptionID)}
}

// Create puts the SAP Central Instance. <br><br>This will be used by service only. PUT by end user will return a Bad
// Request error.
// Parameters:
// resourceGroupName - the name of the resource group. The name is case insensitive.
// sapVirtualInstanceName - the name of the Virtual Instances for SAP.
// centralInstanceName - central Instance name string modeled as parameter for auto generation to work
// correctly.
// body - the SAP Central Server instance request body.
func (client SAPCentralInstancesClient) Create(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string, body *SAPCentralServerInstance) (result SAPCentralInstancesCreateFuture, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/SAPCentralInstancesClient.Create")
		defer func() {
			sc := -1
			if result.FutureAPI != nil && result.FutureAPI.Response() != nil {
				sc = result.FutureAPI.Response().StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	if err := validation.Validate([]validation.Validation{
		{TargetValue: client.SubscriptionID,
			Constraints: []validation.Constraint{{Target: "client.SubscriptionID", Name: validation.MinLength, Rule: 1, Chain: nil}}},
		{TargetValue: resourceGroupName,
			Constraints: []validation.Constraint{{Target: "resourceGroupName", Name: validation.MaxLength, Rule: 90, Chain: nil},
				{Target: "resourceGroupName", Name: validation.MinLength, Rule: 1, Chain: nil}}}}); err != nil {
		return result, validation.NewError("workloads.SAPCentralInstancesClient", "Create", err.Error())
	}

	req, err := client.CreatePreparer(ctx, resourceGroupName, sapVirtualInstanceName, centralInstanceName, body)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Create", nil, "Failure preparing request")
		return
	}

	result, err = client.CreateSender(req)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Create", result.Response(), "Failure sending request")
		return
	}

	return
}

// CreatePreparer prepares the Create request.
func (client SAPCentralInstancesClient) CreatePreparer(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string, body *SAPCentralServerInstance) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"centralInstanceName":    autorest.Encode("path", centralInstanceName),
		"resourceGroupName":      autorest.Encode("path", resourceGroupName),
		"sapVirtualInstanceName": autorest.Encode("path", sapVirtualInstanceName),
		"subscriptionId":         autorest.Encode("path", client.SubscriptionID),
	}

	const APIVersion = "2021-12-01-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsContentType("application/json; charset=utf-8"),
		autorest.AsPut(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Workloads/sapVirtualInstances/{sapVirtualInstanceName}/centralInstances/{centralInstanceName}", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	if body != nil {
		preparer = autorest.DecoratePreparer(preparer,
			autorest.WithJSON(body))
	}
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// CreateSender sends the Create request. The method will close the
// http.Response Body if it receives an error.
func (client SAPCentralInstancesClient) CreateSender(req *http.Request) (future SAPCentralInstancesCreateFuture, err error) {
	var resp *http.Response
	future.FutureAPI = &azure.Future{}
	resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
	if err != nil {
		return
	}
	var azf azure.Future
	azf, err = azure.NewFutureFromResponse(resp)
	future.FutureAPI = &azf
	future.Result = future.result
	return
}

// CreateResponder handles the response to the Create request. The method always
// closes the http.Response Body.
func (client SAPCentralInstancesClient) CreateResponder(resp *http.Response) (result SAPCentralServerInstance, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusCreated),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// Delete deletes the SAP Central Instance. <br><br>This will be used by service only. Delete by end user will return a
// Bad Request error.
// Parameters:
// resourceGroupName - the name of the resource group. The name is case insensitive.
// sapVirtualInstanceName - the name of the Virtual Instances for SAP.
// centralInstanceName - central Instance name string modeled as parameter for auto generation to work
// correctly.
func (client SAPCentralInstancesClient) Delete(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string) (result SAPCentralInstancesDeleteFuture, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/SAPCentralInstancesClient.Delete")
		defer func() {
			sc := -1
			if result.FutureAPI != nil && result.FutureAPI.Response() != nil {
				sc = result.FutureAPI.Response().StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	if err := validation.Validate([]validation.Validation{
		{TargetValue: client.SubscriptionID,
			Constraints: []validation.Constraint{{Target: "client.SubscriptionID", Name: validation.MinLength, Rule: 1, Chain: nil}}},
		{TargetValue: resourceGroupName,
			Constraints: []validation.Constraint{{Target: "resourceGroupName", Name: validation.MaxLength, Rule: 90, Chain: nil},
				{Target: "resourceGroupName", Name: validation.MinLength, Rule: 1, Chain: nil}}}}); err != nil {
		return result, validation.NewError("workloads.SAPCentralInstancesClient", "Delete", err.Error())
	}

	req, err := client.DeletePreparer(ctx, resourceGroupName, sapVirtualInstanceName, centralInstanceName)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Delete", nil, "Failure preparing request")
		return
	}

	result, err = client.DeleteSender(req)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Delete", result.Response(), "Failure sending request")
		return
	}

	return
}

// DeletePreparer prepares the Delete request.
func (client SAPCentralInstancesClient) DeletePreparer(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"centralInstanceName":    autorest.Encode("path", centralInstanceName),
		"resourceGroupName":      autorest.Encode("path", resourceGroupName),
		"sapVirtualInstanceName": autorest.Encode("path", sapVirtualInstanceName),
		"subscriptionId":         autorest.Encode("path", client.SubscriptionID),
	}

	const APIVersion = "2021-12-01-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsDelete(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Workloads/sapVirtualInstances/{sapVirtualInstanceName}/centralInstances/{centralInstanceName}", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// DeleteSender sends the Delete request. The method will close the
// http.Response Body if it receives an error.
func (client SAPCentralInstancesClient) DeleteSender(req *http.Request) (future SAPCentralInstancesDeleteFuture, err error) {
	var resp *http.Response
	future.FutureAPI = &azure.Future{}
	resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
	if err != nil {
		return
	}
	var azf azure.Future
	azf, err = azure.NewFutureFromResponse(resp)
	future.FutureAPI = &azf
	future.Result = future.result
	return
}

// DeleteResponder handles the response to the Delete request. The method always
// closes the http.Response Body.
func (client SAPCentralInstancesClient) DeleteResponder(resp *http.Response) (result OperationStatusResult, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusAccepted, http.StatusNoContent),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// Get gets the SAP Central Instance.
// Parameters:
// resourceGroupName - the name of the resource group. The name is case insensitive.
// sapVirtualInstanceName - the name of the Virtual Instances for SAP.
// centralInstanceName - central Instance name string modeled as parameter for auto generation to work
// correctly.
func (client SAPCentralInstancesClient) Get(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string) (result SAPCentralServerInstance, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/SAPCentralInstancesClient.Get")
		defer func() {
			sc := -1
			if result.Response.Response != nil {
				sc = result.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	if err := validation.Validate([]validation.Validation{
		{TargetValue: client.SubscriptionID,
			Constraints: []validation.Constraint{{Target: "client.SubscriptionID", Name: validation.MinLength, Rule: 1, Chain: nil}}},
		{TargetValue: resourceGroupName,
			Constraints: []validation.Constraint{{Target: "resourceGroupName", Name: validation.MaxLength, Rule: 90, Chain: nil},
				{Target: "resourceGroupName", Name: validation.MinLength, Rule: 1, Chain: nil}}}}); err != nil {
		return result, validation.NewError("workloads.SAPCentralInstancesClient", "Get", err.Error())
	}

	req, err := client.GetPreparer(ctx, resourceGroupName, sapVirtualInstanceName, centralInstanceName)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Get", nil, "Failure preparing request")
		return
	}

	resp, err := client.GetSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Get", resp, "Failure sending request")
		return
	}

	result, err = client.GetResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Get", resp, "Failure responding to request")
		return
	}

	return
}

// GetPreparer prepares the Get request.
func (client SAPCentralInstancesClient) GetPreparer(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"centralInstanceName":    autorest.Encode("path", centralInstanceName),
		"resourceGroupName":      autorest.Encode("path", resourceGroupName),
		"sapVirtualInstanceName": autorest.Encode("path", sapVirtualInstanceName),
		"subscriptionId":         autorest.Encode("path", client.SubscriptionID),
	}

	const APIVersion = "2021-12-01-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsGet(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Workloads/sapVirtualInstances/{sapVirtualInstanceName}/centralInstances/{centralInstanceName}", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// GetSender sends the Get request. The method will close the
// http.Response Body if it receives an error.
func (client SAPCentralInstancesClient) GetSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}

// GetResponder handles the response to the Get request. The method always
// closes the http.Response Body.
func (client SAPCentralInstancesClient) GetResponder(resp *http.Response) (result SAPCentralServerInstance, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// List lists the SAP Central Instances in an SVI.
// Parameters:
// resourceGroupName - the name of the resource group. The name is case insensitive.
// sapVirtualInstanceName - the name of the Virtual Instances for SAP.
func (client SAPCentralInstancesClient) List(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string) (result SAPCentralInstanceListPage, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/SAPCentralInstancesClient.List")
		defer func() {
			sc := -1
			if result.scil.Response.Response != nil {
				sc = result.scil.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	if err := validation.Validate([]validation.Validation{
		{TargetValue: client.SubscriptionID,
			Constraints: []validation.Constraint{{Target: "client.SubscriptionID", Name: validation.MinLength, Rule: 1, Chain: nil}}},
		{TargetValue: resourceGroupName,
			Constraints: []validation.Constraint{{Target: "resourceGroupName", Name: validation.MaxLength, Rule: 90, Chain: nil},
				{Target: "resourceGroupName", Name: validation.MinLength, Rule: 1, Chain: nil}}}}); err != nil {
		return result, validation.NewError("workloads.SAPCentralInstancesClient", "List", err.Error())
	}

	result.fn = client.listNextResults
	req, err := client.ListPreparer(ctx, resourceGroupName, sapVirtualInstanceName)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "List", nil, "Failure preparing request")
		return
	}

	resp, err := client.ListSender(req)
	if err != nil {
		result.scil.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "List", resp, "Failure sending request")
		return
	}

	result.scil, err = client.ListResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "List", resp, "Failure responding to request")
		return
	}
	if result.scil.hasNextLink() && result.scil.IsEmpty() {
		err = result.NextWithContext(ctx)
		return
	}

	return
}

// ListPreparer prepares the List request.
func (client SAPCentralInstancesClient) ListPreparer(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"resourceGroupName":      autorest.Encode("path", resourceGroupName),
		"sapVirtualInstanceName": autorest.Encode("path", sapVirtualInstanceName),
		"subscriptionId":         autorest.Encode("path", client.SubscriptionID),
	}

	const APIVersion = "2021-12-01-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsGet(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Workloads/sapVirtualInstances/{sapVirtualInstanceName}/centralInstances", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// ListSender sends the List request. The method will close the
// http.Response Body if it receives an error.
func (client SAPCentralInstancesClient) ListSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}

// ListResponder handles the response to the List request. The method always
// closes the http.Response Body.
func (client SAPCentralInstancesClient) ListResponder(resp *http.Response) (result SAPCentralInstanceList, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// listNextResults retrieves the next set of results, if any.
func (client SAPCentralInstancesClient) listNextResults(ctx context.Context, lastResults SAPCentralInstanceList) (result SAPCentralInstanceList, err error) {
	req, err := lastResults.sAPCentralInstanceListPreparer(ctx)
	if err != nil {
		return result, autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "listNextResults", nil, "Failure preparing next results request")
	}
	if req == nil {
		return
	}
	resp, err := client.ListSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		return result, autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "listNextResults", resp, "Failure sending next results request")
	}
	result, err = client.ListResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "listNextResults", resp, "Failure responding to next results request")
	}
	return
}

// ListComplete enumerates all values, automatically crossing page boundaries as required.
func (client SAPCentralInstancesClient) ListComplete(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string) (result SAPCentralInstanceListIterator, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/SAPCentralInstancesClient.List")
		defer func() {
			sc := -1
			if result.Response().Response.Response != nil {
				sc = result.page.Response().Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	result.page, err = client.List(ctx, resourceGroupName, sapVirtualInstanceName)
	return
}

// Update updates the SAP Central Instance. <br><br>This can be used to update tags.
// Parameters:
// resourceGroupName - the name of the resource group. The name is case insensitive.
// sapVirtualInstanceName - the name of the Virtual Instances for SAP.
// centralInstanceName - central Instance name string modeled as parameter for auto generation to work
// correctly.
// body - the SAP Central Server instance request body.
func (client SAPCentralInstancesClient) Update(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string, body *UpdateSAPCentralInstanceRequest) (result SAPCentralInstancesUpdateFuture, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/SAPCentralInstancesClient.Update")
		defer func() {
			sc := -1
			if result.FutureAPI != nil && result.FutureAPI.Response() != nil {
				sc = result.FutureAPI.Response().StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	if err := validation.Validate([]validation.Validation{
		{TargetValue: client.SubscriptionID,
			Constraints: []validation.Constraint{{Target: "client.SubscriptionID", Name: validation.MinLength, Rule: 1, Chain: nil}}},
		{TargetValue: resourceGroupName,
			Constraints: []validation.Constraint{{Target: "resourceGroupName", Name: validation.MaxLength, Rule: 90, Chain: nil},
				{Target: "resourceGroupName", Name: validation.MinLength, Rule: 1, Chain: nil}}}}); err != nil {
		return result, validation.NewError("workloads.SAPCentralInstancesClient", "Update", err.Error())
	}

	req, err := client.UpdatePreparer(ctx, resourceGroupName, sapVirtualInstanceName, centralInstanceName, body)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Update", nil, "Failure preparing request")
		return
	}

	result, err = client.UpdateSender(req)
	if err != nil {
		err = autorest.NewErrorWithError(err, "workloads.SAPCentralInstancesClient", "Update", result.Response(), "Failure sending request")
		return
	}

	return
}

// UpdatePreparer prepares the Update request.
func (client SAPCentralInstancesClient) UpdatePreparer(ctx context.Context, resourceGroupName string, sapVirtualInstanceName string, centralInstanceName string, body *UpdateSAPCentralInstanceRequest) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"centralInstanceName":    autorest.Encode("path", centralInstanceName),
		"resourceGroupName":      autorest.Encode("path", resourceGroupName),
		"sapVirtualInstanceName": autorest.Encode("path", sapVirtualInstanceName),
		"subscriptionId":         autorest.Encode("path", client.SubscriptionID),
	}

	const APIVersion = "2021-12-01-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsContentType("application/json; charset=utf-8"),
		autorest.AsPatch(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Workloads/sapVirtualInstances/{sapVirtualInstanceName}/centralInstances/{centralInstanceName}", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	if body != nil {
		preparer = autorest.DecoratePreparer(preparer,
			autorest.WithJSON(body))
	}
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// UpdateSender sends the Update request. The method will close the
// http.Response Body if it receives an error.
func (client SAPCentralInstancesClient) UpdateSender(req *http.Request) (future SAPCentralInstancesUpdateFuture, err error) {
	var resp *http.Response
	future.FutureAPI = &azure.Future{}
	resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
	if err != nil {
		return
	}
	var azf azure.Future
	azf, err = azure.NewFutureFromResponse(resp)
	future.FutureAPI = &azf
	future.Result = future.result
	return
}

// UpdateResponder handles the response to the Update request. The method always
// closes the http.Response Body.
func (client SAPCentralInstancesClient) UpdateResponder(resp *http.Response) (result SAPCentralServerInstance, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusCreated),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}
